name: store_responsive_dashboard
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"  # Updated to support latest versions

dependencies:
  flutter:
    sdk: flutter

  # Add SQLite3 dependencies suitable for desktop application
  sqlite3: ^2.4.7  # Ensure compatibility with newer SDK
  sqlite3_flutter_libs: ^0.5.0

  # UI dependencies
  cupertino_icons: ^1.0.2
  fl_chart: ^0.69.0
  flutter_staggered_grid_view: ^0.7.0
  printing: ^5.13.4  # Updated to the latest version with Windows support

  # State management
  provider: ^6.1.0  # Update to the latest stable version

  # Date formatting and localization
  intl: ^0.19.0

  # Path Provider for file system access (added for client database and receipt paths)
  path_provider: ^2.0.13  # General path_provider instead of platform-specific to ensure compatibility
  path_provider_windows: ^2.3.0  # Keep for specific Windows support

  # JSON serialization
  json_serializable: ^6.6.1  # Update to the latest stable version

  # Screenshot package for capturing widget screenshots
  screenshot: ^3.0.0  # Reverted to a stable version that exists

  # Windows specific dependencies
  win32: ^5.8.0  # Updated to be compatible with pdfx package

  # Syncfusion PDF package for PDF generation
  pdf: ^3.11.1  # Add this line to use the pdf package

  pdfx: ^2.8.0

  # **Added Dependencies**
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # For testing purposes
  async: ^2.11.0
  boolean_selector: ^2.1.1
  clock: ^1.1.1
  fake_async: ^1.3.1
  matcher: ^0.12.16+1
  stack_trace: ^1.10.0
  string_scanner: ^1.1.0
  test_api: ^0.7.2  # Downgraded to align with other dependencies
  leak_tracker: ^10.0.5
  leak_tracker_flutter_testing: ^3.0.5
  vm_service: ^14.2.5

flutter:
  uses-material-design: true

  # Ensure this directory exists for storing images like receipts
  assets:
    - assets/imgs/

  # Correctly configured font assets
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: ArialUnicodeMS
      fonts:
        - asset: assets/fonts/arial-unicode-ms.ttf
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-VariableFont_wdth,wght.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: KurdishBold
      fonts:
        - asset: assets/fonts/K24KurdishBold-Bold.ttf
